title: SBMLDEV
description: "Site for SBML Project"
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

minimal_mistakes_skin: "default"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

include:
  - _pages

footer:
  links: false
  content: "© 2025 SBML"

permalink: /:title/
