title: sbmldev
description: "A GitHub Pages site using Minimal Mistakes"
baseurl: ""
url: "https://sbml.dev"
repository: "sbmldev/sbml-site"

# Theme
remote_theme: mmistakes/minimal-mistakes

# Build settings
plugins:
  - jekyll-include-cache

# Author (Optional)
author:
  name: sbmldev

# Minimal Mistakes settings
minimal_mistakes_skin: dark

# Navigation (optional)
nav:
  - title: "Home"
    url: "/"
