title: ""
description: "Site for SBML Project"
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

minimal_mistakes_skin: "custom"

search: true
search_provider: lunr

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

include:
  - _pages

footer:
  content: "© 2025 sbmldev"

permalink: /:title/
