title: SBML
description: "Site for SBML Project"
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
minimal_mistakes_skin: "default"
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
include:
  - _pages
permalink: /:title/
