title: ""
description: "Site for SBML Project"
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

minimal_mistakes_skin: "custom"

search: true
search_provider: lunr

header:
  nav:
    - main

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

include:
  - _pages

collections:
  pages:
    output: true
    permalink: /:path/

footer:
  content: "© 2025 sbmldev"

permalink: /:title/

